apiVersion: ray.io/v1
kind: RayService
metadata:
  name: ray-serve-llm
spec:
  serveConfigV2: |
    applications:
    - name: llms
      import_path: ray.serve.llm:build_openai_app
      route_prefix: "/"
      args:
        llm_configs:
        - model_loading_config:
            model_id: Qwen2.5VL3B
            model_source: /models/Qwen2.5VL3B/snapshots/66285546d2b821cf421d4f5eb2576359d3770cd3/
          engine_kwargs:
            dtype: half
            max_model_len: 1024
            device: auto
            gpu_memory_utilization: 0.9
          deployment_config:
            autoscaling_config:
              min_replicas: 1
              max_replicas: 1
              target_ongoing_requests: 16
            max_ongoing_requests: 32
  rayClusterConfig:
    rayVersion: "2.46.0"
    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        num-gpus: "0"
      template:
        spec:
          volumes:
          - name: models-storage-volume
            persistentVolumeClaim:
              claimName: s3-models-pvc
          containers:
          - name: ray-head
            image: 010526271896.dkr.ecr.ap-south-1.amazonaws.com/rayproject/ray-llm:2.46.0-py311-cu124
            volumeMounts:
            - name: models-storage-volume
              mountPath: /models
            ports:
            - containerPort: 8000
              name: serve
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 6379
              name: gcs
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            - containerPort: 10001
              name: client
              protocol: TCP
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 1
      numOfHosts: 1
      groupName: gpu-group
      rayStartParams:
        num-gpus: "1"
      template:
        spec:
          nodeSelector:
            karpenter.sh/nodepool: gpu-pool-l40s
          tolerations:
            - key: "nvidia.com/gpu"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
          volumes:
          - name: models-storage-volume
            persistentVolumeClaim:
              claimName: s3-models-pvc
          containers:
          - name: ray-worker
            image: 010526271896.dkr.ecr.ap-south-1.amazonaws.com/rayproject/ray-llm:2.46.0-py311-cu124
            volumeMounts:
            - name: models-storage-volume
              mountPath: /models
            resources:
              limits:
                cpu: 4
                memory: 12Gi
                nvidia.com/gpu: "1"
              requests:
                cpu: 4
                memory: 12Gi
                nvidia.com/gpu: "1"

