apiVersion: ray.io/v1
kind: RayService
metadata:
  name: ray-serve-llm
spec:
  serveConfigV2: |
    applications:
    - name: llms
      import_path: ray.serve.llm:build_openai_app
      route_prefix: "/"
      args:
        llm_configs:
        - model_loading_config:
            model_id: olmOCR-7B-0225-preview
            model_source: /models/olmOCR-7B-0225-preview/
          engine_kwargs:
            max_model_len: 8192
            device: auto
            gpu_memory_utilization: 0.9
            pipeline_parallel_size: 2 
            swap_space: 12
          deployment_config:
            num_replicas: 1
            max_ongoing_requests: 32
  rayClusterConfig:
    rayVersion: "2.46.0"
    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        num-gpus: "0"
      template:
        spec:
          volumes:
          - name: models-storage-volume
            persistentVolumeClaim:
              claimName: s3-models-pvc
          containers:
          - name: ray-head
            image: 010526271896.dkr.ecr.ap-south-1.amazonaws.com/rayproject/ray-llm:2.46.0-py311-cu124
            volumeMounts:
            - name: models-storage-volume
              mountPath: /models
            ports:
            - containerPort: 8000
              name: serve
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 6379
              name: gcs
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            - containerPort: 10001
              name: client
              protocol: TCP
            resources:
              limits:
                cpu: 4
                memory: 16Gi
              requests:
                cpu: 4
                memory: 16Gi
    workerGroupSpecs:
    - replicas: 2
      minReplicas: 1
      maxReplicas: 3
      groupName: gpu-group
      rayStartParams:
        num-gpus: "1"
        num-cpus: "8"
      template:
        spec:
          nodeSelector:
            karpenter.sh/nodepool: gpu-pool-l40s
          tolerations:
            - key: "nvidia.com/gpu"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
          volumes:
          - name: models-storage-volume
            persistentVolumeClaim:
              claimName: s3-models-pvc
          - name: shm
            emptyDir:
              medium: Memory
              sizeLimit: 15Gi
          containers:
          - name: ray-worker
            image: 010526271896.dkr.ecr.ap-south-1.amazonaws.com/rayproject/ray-llm:2.46.0-py311-cu124
            volumeMounts:
            - name: models-storage-volume
              mountPath: /models
            - name: shm
              mountPath: /dev/shm
            resources:
              limits:
                cpu: 8
                memory: 32Gi
                nvidia.com/gpu: "1"
              requests:
                cpu: 8
                memory: 32Gi
                nvidia.com/gpu: "1"

