apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadOnlyMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: s3-test # Namespace is required even though it's in "default" namespace.
    name: s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region ap-south-1
    - prefix models/
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume # Must be unique
    volumeAttributes:
      bucketName: aws-huggingface-models
      stsRegion: ap-south-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: s3-test 
spec:
  accessModes:
    - ReadOnlyMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: s3-pv # Name of your PV
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-csi-admin-sa
  namespace: s3-test
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::010526271896:role/AmazonEKS_S3_CSI_DriverRole"
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-app
  namespace: s3-test
spec:
  containers:
    - name: app
      image: 010526271896.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-pvc
